### ISSUE TITLE
Bug - Handling of URI with https:// - An error has occurred: Absolute URI missing hierarchical segment: 'http://'

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#12]
After updating to v0.10.0 I am seeing a number of times that the program fails to complete the check for broken links. The error returned is:

> An error has occurred: Absolute URI missing hierarchical segment: 'http://'

Interesting this this occurs when using a URI that is using a SSL connection starting with `https://`, so I am wondering why it is giving an error about not containing a non-SSL URI. 

I think that this is related to a external program that it is using as I cannot find that error text in the `broken_link_finder` code on github by searching for it or sections of it.

I tested by running the command over a day once per hour with my wrapper script and also in testing on the command line without the wrapper script (ie. `broken_link_finder crawl --recursive --html --sort-by-link https://example.com`). The result was 28 fails out of 46 runs.

I also found that then the error above is returned that broken_link_finder is exiting with a OK status code of **0**, the same if everything functioned correctly and a report of broken links was returned. 

This means that when I use [cronic](https://habilis.net/cronic/) when running this with `cron` it will not email me that there was an error. This is not the way I believe this should function.

**Comment by michaeltelford** [comment]
@frederickjh Yes you're right. The return status code should return an error status on error; and also possibly reflect whether or not broken links were found (in absence of an error). This will be fixed in a future release.

As for the error you're seeing, can you send me (via email at michael.telford@live.com) the URL you were crawling please (so I can test it; as I've not seen this error before)?

**Comment by frederickjh** [comment]
I left my cron job running each hour since I last posted. It ran 98 times and of those 62 resulted in an error and no report. One of the errors was (sanitized):

> An error has occurred: Invalid or broken URL: https://www.example.com **

 but the rest of the errors were as reported above:

> An error has occurred: Absolute URI missing hierarchical segment: 'http://'

**Comment by michaeltelford** [comment]
The `broken_link_finder` executable exit codes have been fixed and will be in the next release. Now, if the code errors a `1` code will be returned, otherwise if the code completes, a `0` code will be returned (as is standard practice on Unix based machines).

**Comment by michaeltelford** [comment]
> An error has occurred: Absolute URI missing hierarchical segment: 'http://'

This issue has been fixed and will be in the next release.

> An error has occurred: Invalid or broken URL: https://www.example.com **

This error means the URL you've passed to the executable isn't valid or produces a response other than `200 OK`. If this happens again, try `curl`ing the same URL, if `curl` can't hit it either then it's the website. Otherwise, raise a bug here and send me the URL your were testing with.

**Comment by michaeltelford** [comment]
@frederickjh FYI ^^^

The next release will be out in a matter of days.

**Comment by michaeltelford** [comment]
All issues above have been addressed in the latest release. From the CHANGELOG:

## v0.11.0
### Added
- Additional crawl statistics.
- Exit code handling to executable. `0` for success, `1` for an error scenario.
### Changed/Removed
- Updated the report formats slightly bringing various improvements such as the total number of links crawled etc.
### Fixed
- Bug in html report, summary url is now an `<a>` link.
- Bug in `Finder@broken_link_map` URLs and `Finder#crawl_stats[:url]` URL during redirects.
- Bug causing an error on crawling unparsable/invalid URL's.
---

@frederickjh  FYI ^^^

**Comment by frederickjh** [comment]
I ran a test overnight once per hour and had no errors. Thanks for fixing this @michaeltelford !
