### ISSUE TITLE
Consider offering a compiled binary for broken_link_finder

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#15]
@michaeltelford I have been more than happy with broken_link_finder, but I am now in a position where I need to move my broken link checking to a server where I do not have super user permissions. Trying to setup a ruby environment in this situation is not a trivial mater and I believe it is not even possible in my case.

I see that there are a few projects to compile Ruby programs into a portable binary that could be run without a full ruby install. This request is to ask you to consider offering a compiled binary for broken_link_finder. This too does not seem like a trivial mater. With my limited Ruby knowledge and experience it does not seem to make sense for me to spend the time and effort to just compile this for my work. It would make more sense to do this at the project level, as this would allow adoption of the program at a higher level.  

If this is not something that you are interested in doing just close this issue.
Thanks for your consideration!
Frederick

**Comment by michaeltelford** [comment]
One of the obvious dependencies for broken_link_finder is a working Ruby installation. It's isn't realistic to expect a Ruby repository to provide a Ruby installation just so the code can be run; This is a project in itself as there's many things to consider, like which OS platforms and versions to support etc. etc. I don't know of any other Ruby libraries/gems that do this, probably for these reasons. Therefore I won't be adding a binary for broken_link_finder to the repository and will close close this issue.

However, I don't mind spending a limited amount of my personal time to help you out @frederickjh, if I can. So send me an email at michael.telford@live.com about the OS you're using and I'll see what I can do. Also, ensure you have the necessary permissions to run the binary if we can get it built for you.

**Comment by frederickjh** [comment]
@michaeltelford  Thanks for the offer of help, however I think I will pass. I don't want to create a Frankenstein that no one can later replicate nor update. I was not sure if you had worked with one of the Ruby projects (Traveling Ruby, rake-compiler, Ruby Packer, etc.)  that compiles Ruby programs to portable binaries, which as you said include Ruby.
