### ISSUE TITLE
Protocol relative links are reported as missing and linked incorrectly in email reports

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#16]
In one of the broken link reports that normally gets sent to website owner (which I had personally not looked at for some time) I found the following:

> The broken link '//s.w.org' was found on the following pages:

This link is not really broken. I found that this type of links are what are called protocol relative links. In other words depending on if the document containing them is using the http or https the same protocol would be used for these protocol relative links. Using these type of links in modules and add-ons for CMS is best practice to avoid the mix-content error.

@michaeltelford This is a new thing for me. I had never heard about protocol relative links until I research this today.

The link for this broken link in the email was also incorrect. ie. it linked to something like https://example.com//fonts.googleapis.com when it should have linked to https://fonts.googleapis.com

**Comment by frederickjh** [comment]
[Blog post](https://www.paulirish.com/2010/the-protocol-relative-url/) about protocol relative links that references [RFC 3986](https://tools.ietf.org/html/rfc3986#section-4.2).

**Comment by michaeltelford** [comment]
Hi @frederickjh. Yes, this is an issue that needs addressing. I will take a look and update this issue when it's fixed in the next release of `broken_link_finder`.

**Comment by michaeltelford** [comment]
Note to self: Also update the `README'`s Installation section with info on the supported versions of Ruby.

**Comment by michaeltelford** [comment]
This is now fixed in the `broken_link_finder v0.12.0` gem @frederickjh.

**Comment by frederickjh** [comment]
Thanks @michaeltelford this works as expected. I just tested it on the same site and it no longer reports protocol relative links as broken. :sunglasses:
