### ISSUE TITLE
Only broken href links to other domains are reported

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#2]
Hi!
I setup a test page to test the different types of broken links and combinations thereof.  Links to the same site, to external sites, links to anchors and links to images. Of the seven broken links that all return a 404 checked with `curl -I` only two were reported as broken.

* Images that were missing were not reported.
* Broken links on the same domain were not reported.
* Links to external sites were were reported as broken.

**Comment by michaeltelford** [comment]
Hi,

Can you paste/attach the full HTML test file you’re using please?

Thanks,
Michael

**Comment by frederickjh** [comment]
Hi @michaeltelford,
I realized that I had forgotten to include relative links to the test domain and broken links to a domain that exists that are broken. I have updated the test page. Which I have sent a link to in a private email along with the source code.
I hope this helps!
Frederick

**Comment by michaeltelford** [comment]
Hi Frederick,

Thanks for the email and the test page, it’s a great help.

I will look into this ASAP.

Thanks,
Michael

On 13 Jul 2019, at 3:46 pm, Frederick Henderson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @michaeltelford<https://github.com/michaeltelford>,
I realized that I had forgotten to include relative links to the test domain and broken links to a domain that exists that are broken. I have updated the test page. Which I have sent a link to in a private email along with the source code.
I hope this helps!
Frederick

**Comment by michaeltelford** [comment]
Hi Frederick,

Thanks for this, the test page is a great help. 

I will look into this ASAP. 

Thanks,
Michael

**Comment by frederickjh** [comment]
There are 17 broken links on the test page. The broken link checker at [error404.atomseo.com]( https://error404.atomseo.com/) finds them all. It classifies them as, 9 internal links, 4 external links, 4 broken anchors. Some of these apear twice as I have absolute and relative links of the same broken links. I sent a copy of the report to you via email.

**Comment by frederickjh** [comment]
I just realized that the  online service  error404.atomseo.com does not check `<img src=` tags. [drlinkcheck.com](https://www.drlinkcheck.com/) does check image src link. Try running the test page on it. It finds 5 broken image links in addition to the ones I listed in my last comment.

`broken_link_finder` is only finding two broken links on the test page which are classify by drlinkcheck.com as **Host not found**.

**Comment by frederickjh** [comment]
drlinkcheck.com does not check anchor links but between the two it is possible to check them all.

**Comment by frederickjh** [comment]
I just realized that error404.atomseo.com is checking image links. I found them listed with the other broken links.

**Comment by michaeltelford** [comment]
As of `broken_link_finder v0.5.0` the above issues have been addressed. This version includes:

- Any element with a `href` or `src` attribute is now regarded as a link. Before it was just `<a>` elements.
- Anchor support is now included meaning the response HTML must include an element with an ID matching that of the anchor in the link's URL; otherwise, it's regarded as broken. Previously, there was no anchor support.
- The `README` now includes a **How It Works** section detailing what constitutes a broken link. See this for more information.

@frederickjh I will follow up your email shortly to discuss the specifics of the test page that you set up for this. We can discuss the status of this issue in the emails.

**Comment by frederickjh** [comment]
@michaeltelford Good to hear. I will run some real world test with it on Monday and let you know how it works out compared to the wget script I have also used for this.

**Comment by frederickjh** [comment]
@michaeltelford I have run some test and found the following points that I think need addressed. I have sent you an email with more information from reports that I have run with _broken_link_finder_.

- Anchors are listed in the report with broken links. Of course an anchor cannot have broken links in it. The list is a duplicate of the links on the page where it is located.
- mailto: links are reported as broken even thought they have correct html and open a mail program.
- It is currently searching **.js** files text for links. I saw one in a comment and the others appeared to be selectors. Not sure if searching **.js** for links is needed.
- tel: links are reported as broken even though they open the telephone app on cellphones.
- ftp: links are reported as broken. This is a bit tricky, as FTP servers have their own list of [return codes](https://en.wikipedia.org/w/index.php?title=List_of_FTP_server_return_codes). Which are not the same as the [HTTP return codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). The one link I have on to a ftp site requires a login so running 

`curl -I ftp://example.com`

 on it to test returns, 

`curl: (67) Access denied: 530`

which **530** is the correct FTP return code for "**Not logged in (or Password Rejected)**". This however is not a broken link. It exists but requires a login.

_broken_link_finder_ currently finding more broken links (even without the falsely reported links)  than a script I have used with wget that uses the following to do the heavy lifting:
```
wget --spider -r -nd -nv -e robots=off https://example.com
```
Thanks again for your hard work on this!
Frederick

**Comment by michaeltelford** [comment]
`broken_link_finder v0.6.0` has the following improvements:

- Support for ignored links e.g. `mailto`'s, `tel`'s etc. The `README` has been updated. 
- Links with anchors aren't regarded as separate pages during a crawl anymore, thus removing duplicate reports. 
- Only HTML files now have their links verified, JS files for example, do not have their contents checked. This also boosts crawl speed.
- Links are now reported exactly as they appear in the HTML (for easier location after reading the reports)

@frederickjh This version should address the issues you raised above. If you could re-run your tests and verify that would be great! Thanks.

**Comment by frederickjh** [comment]
I ran the test page and a couple of websites through broken_link_finder. It is looking a lot different to the first version that I downloaded and filed this issue against, 0.4.1. @michaeltelford,  I will send you an email with more information from the test reports regarding my comments below.

### Possibly add option to reduce noise for ignored links in reports
I am wondering if the handling of the ignored links could have an option to turn down the noise in the report. Maybe an option to turn on a CMS (content management system) report option for the ignored links. I have an email and a telephone link in the footer of the page which means it appears on every page on the site, which means the report for ignored links is quite big. I think that if there is too much noise in these report that will get sent to content creator that they may miss the other links that should be fixed.  
With the CMS option I see something like the  following  happening for ignored links in reports. If the ignored link is found multiple times, the first page it is found on is reported and the output in the report would say it was found on multiple pages, possibly with the number of times it was found.

### 301 for anchor link report incorrectly as broken
In the reports that came back I found that an anchor link that the site was forwarding (301) to another page that returned a (200) was being reported as broken. The content editor had not entered the language prefix to the path. The CMS returned a 301 with the language prefix added to the path

### Query strings on URL cause duplicate listings for broken links
Related to the above, the same page with that 301 anchor link also has a webform that we pre-fill using query strings in the URL. Each unique query string added a line to the report. I think that these duplicates (same URL different query strings) should not be report individually in the report. I think that it should be only reported once without the query string in the report.

**Comment by michaeltelford** [comment]
OK, having looked into the 3 issues listed above:

### 301 for anchor link report incorrectly as broken

Upon investigation, this link is broken and is correctly reported because the page doesn't have an element whose ID matches that of the URL anchor. No changes needed.

### Query strings on URL cause duplicate listings for broken links

Query strings are included in the reports as separate pages because they technically are separate pages. Unlike URL anchors (which are client-side), the query string params (processed by the server) can change a page's content and resulting links. Therefore, they're treated separately from other pages with the same URL but different query parameters. A good example of this is the `?q="dog food"` query param on Google's search page. No changes needed.

The main issue here is that the reports are too noisy, which is addressed below.

### Possibly add option to reduce noise for ignored links in reports

I agree that the current report format is too noisy for larger sites. Therefore I will implement some additional flags on the `broken_link_finder` executable to reduce some of the noise for both broken and ignored links. I will update this issue when these changes have been made in the next release.

**Comment by michaeltelford** [comment]
As of `broken_link_finder v0.7.0` the following changes have been implemented:

## v0.7.0
### Added
- Added the `--verbose` flag to the executable for displaying all ignored links.
- Added the `--concise` flag to the executable for displaying the broken links in summary form.
- Added the `--sort-by-link` flag to the executable for displaying the broken links found and the pages containing that link (as opposed to sorting by page by default).
### Changed/Removed
- Changed the **default** sorting (format) for ignored links to be summarised (much more concise) reducing noise in the reports.
- Updated the `README.md` to reflect the new changes.
### Fixed
- Bug where the broken/ignored links weren't being ordered consistently between runs. Now, all links are reported alphabetically. This will change existing report formats.
- Bug where an anchor of `#` was being returned as broken when it shouldn't.

@frederickjh this should make the reports more concise. Can you confirm and please update this issue?

**Comment by frederickjh** [comment]
@michaeltelford Yes these changes do make the reports more concise. Using the `--sort-by-link` gets me what I want in a broken links report. I have two other issues that I found but I will open new issues for these.
