### ISSUE TITLE
Reports sometimes show link protocol as http:// even thought link protocol given on the command line was https://

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#3]
When I run a report like this:
```
broken_link_finder crawl --recursive --sort-by-link https://example.com
```
For some sites the report shows the protocol for the links as `http://` even thought the sites' .htaccess file redirects all request to the SSL version of the site and the protocol `https://` was given on the command line.

Other sites report back the links with the SSL protocol of `https://`.

Which protocol Is broken_link_finder using when it checks the links? Is there a reason it would fallback to the `http://` protocol instead of use the requested protocol of `https://`?

**Comment by michaeltelford** [comment]
`broken_link_finder` will use the protocol provided by the link. It doesn't change the protocol. If a `http` link/URL redirects to a `https` URL then `https` will be used on the second hop of the crawl in determining if the link is broken or not. Relative URLs like `/admin` will take the protocol of the main URL passed to the executable.

One thing to remember however, is that the original link will be reported (if broken), not the redirected to URL. This is deliberate, so you can find and fix the broken link on your site. Perhaps this accounts for the different protocol you're seeing?

**Comment by frederickjh** [comment]
I find it strange that the links reported as broken come back with http:// as the .htaccess file redirects all links to https://. I ran the check with a URI with https://.

In any case I will email you the report so you can check it yourself.

**Comment by frederickjh** [comment]
I just ran another report and the links all came back with https://, I checked and I have two reports for the same site with all http:// so I am going to assume that I must have mistakenly ran it with that protocol. However I can not find in my shell history any record of running it with http://. 

I am therefore going to close this issue, but will reopen if I find that it happens again and I am certain that the check was run with https://.
